apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-statefulset
  namespace: redis
spec:
  template:
    spec:
      containers:
        - name: redis
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
