apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
  labels:
    app: zkless-kafka
spec:
  ports:
    - name: kafka
      protocol: TCP
      port: 9092
      targetPort: 9092
    - name: zk
      protocol: TCP
      port: 2181
      targetPort: 2181
    - name: jmx
      protocol: TCP
      port: 9999
      targetPort: 9999
  selector:
    app: zkless-kafka
  type: NodePort
