apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-eagle-data-pv-claim
  labels:
    app: kafka-eagle
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
