apiVersion: v1
kind: Service
metadata:
  name: kafka-eagle-svc
  labels:
    app: kafka-eagle
spec:
  type: NodePort
#  type: ClusterIP
#  type: LoadBalancer
  ports:
    - port: 8048
      targetPort: 8048
      nodePort: 30048
  selector:
    app: kafka-eagle

