version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.193
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      #KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
    volumes:
      - ./config:/opt/myConfig
    working_dir: /opt/kafka
  kafka-eagle:
    image: gui66497/kafka_eagle
    # image: rottenleaf/kafka-eagle:2.0.3
    container_name: ke
    restart: always
    depends_on:
      - kafka
    ports:
      - "8048:8048"
    environment:
      ZKSERVER: "zookeeper:2181"
    # volumes:
    #   - ./system-config.properties:/kafka-eagle/conf/system-config.properties
    #   - ./logs:/kafka-eagle/logs